// Code generated by mockery v1.0.0. DO NOT EDIT.

package common

import (
	image "image"
	io "io"

	mock "github.com/stretchr/testify/mock"

	os "os"
)

// MockOS is an autogenerated mock type for the OS type
type MockOS struct {
	mock.Mock
}

// Create provides a mock function with given fields: name
func (_m *MockOS) Create(name string) (*os.File, error) {
	ret := _m.Called(name)

	var r0 *os.File
	if rf, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encode provides a mock function with given fields: w, m
func (_m *MockOS) Encode(w io.Writer, m image.Image) error {
	ret := _m.Called(w, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, image.Image) error); ok {
		r0 = rf(w, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
